argocd:
  namespace: vault

vault:
  nameOverride: vault
  fullnameOverride: vault
  kubeNamespace: vault

server:
  affinity: ""
  ha:
    enabled: true
    replicas: 1
    config: |
      ui = true
      listener "tcp" {
        tls_disable = 1
        address = "[::]:8200"
        cluster_address = "[::]:8201"
      }
      storage "consul" {
        tls_skip_verify = "true"
        path = "vault"
        scheme = "https"
        address = "HOST_IP:8501"
      }
      service_registration "kubernetes" {}
  extraSecretEnvironmentVars:
    - envName: CONSUL_HTTP_TOKEN
      secretName: vault-storage-token
      secretKey: CONSUL_HTTP_TOKEN
ui:
  enabled: true

